// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcCongresoTIC.Data;

#nullable disable

namespace MvcCongresoTIC.Migrations
{
    [DbContext(typeof(MvcCongresoTICContext))]
    partial class MvcCongresoTICContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcCongresoTIC.Models.Conferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ConfirmacionAsistencia")
                        .HasColumnType("bit");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreConferencista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Conferencia");
                });

            modelBuilder.Entity("MvcCongresoTIC.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TYC")
                        .HasColumnType("bit");

                    b.Property<string>("UTwitter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Participante");
                });

            modelBuilder.Entity("MvcCongresoTIC.Models.RegistroConferencia", b =>
                {
                    b.Property<int>("ConferenciaId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("int");

                    b.Property<int?>("ConferenciaId1")
                        .HasColumnType("int");

                    b.Property<bool>("ConfirmacionAsistencia")
                        .HasColumnType("bit");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("ConferenciaId", "ParticipanteId");

                    b.HasIndex("ConferenciaId1");

                    b.HasIndex("ParticipanteId");

                    b.ToTable("RegistrosConferencias");
                });

            modelBuilder.Entity("MvcCongresoTIC.Models.RegistroConferencia", b =>
                {
                    b.HasOne("MvcCongresoTIC.Models.Conferencia", "Conferencia")
                        .WithMany("Asistentes")
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MvcCongresoTIC.Models.Conferencia", null)
                        .WithMany("AsistentesCollection")
                        .HasForeignKey("ConferenciaId1");

                    b.HasOne("MvcCongresoTIC.Models.Participante", "Participante")
                        .WithMany("RegistrosConferencias")
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("MvcCongresoTIC.Models.Conferencia", b =>
                {
                    b.Navigation("Asistentes");

                    b.Navigation("AsistentesCollection");
                });

            modelBuilder.Entity("MvcCongresoTIC.Models.Participante", b =>
                {
                    b.Navigation("RegistrosConferencias");
                });
#pragma warning restore 612, 618
        }
    }
}
